name: test-go
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v4
                        - uses: actions/setup-go@v5
                          id: setup-go
                          with:
                            go-version-file: go.mod
                        - name: Douwnload Go modules
                          shell: bash
                          if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
                          run: go mod download
                        
                        - run: go version
                        - run: go test